config/routes.rb
Rails.application.routes.draw do
  
  root "kittens#index"
  resources :kittens
end

app/models/kitten.rb
class Kitten < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render :json => @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      redirect_to @kitten, notice: 'Kitten was successfully created.'
    else
      render :new
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update_attributes(kitten_params)
      redirect_to @kitten, notice: 'Kitten was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    Kitten.find(params[:id]).destroy
    redirect_to kittens_url
  end

  private

    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/edit.html.erb
<h1>Edit kitten</h1>
<%= form_for @kitten do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :cuteness %>
  <%= f.select :cuteness, 1..5 %>

  <%= f.label :softness %>
  <%= f.select :softness, 1..5 %>

  <%= f.submit "Submit" %>

<% end %>

app/views/kittens/index.html.erb
<h1>Kittens</h1>
<% @kittens.each do |kitten| %>
  <ul>
    <li><%= link_to kitten.name, kitten %></li>
  </ul>
<% end %>
<%= link_to "New Kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<h1>New kitten</h1>
<%= form_for @kitten do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :cuteness %>
  <%= f.select :cuteness, 1..5 %>

  <%= f.label :softness %>
  <%= f.select :softness, 1..5 %>

  <%= f.submit "Create" %>

<% end %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>

<p>Age: <%= @kitten.age %></p>
<p>Cuteness: <%= @kitten.cuteness %></p>
<p>Softness: <%= @kitten.softness %></p>

<%= link_to "Back", kittens_path %> |
<%= link_to "Edit", edit_kitten_path(@kitten) %> |
<%= link_to "Delete", @kitten, method: :delete,
                                  data: { confirm: "Are you sure?" } %>

app/views/kittens/update.html.erb
<h1>Kittens#update</h1>
<p>Find me in app/views/kittens/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OdinKittens</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>